using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace nilnul.dev.sln.div.dir_
{
	/// <summary>
	/// the dir inside a div might be noncandidate:
	///		enclave(such as .nilnul/)
	///		,
	///		nonconsidered|unlisted per .nilnul cfg
	///		,
	///		repo
	///		,
	///		autogenerated by tools. <see cref="nilnul.fs.folder.dir_.artifact"/>
	///	if it's not noncandidate, then 
	/// we now consider this dir as candidate. 
	/// </summary>
	/// alias:
	///		before delve
	///		pre-delve
	///		enrolled
	///			, as child is 入嗣
	///		conscript
	///		manual
	///		artifact
	internal class ICandidate
	{
	}
}
