using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace nilnul.dev.src.sln.div_
{
	/// <summary>
	/// each dir is <see cref="listable"/> as well as <see cref="notDotLed"/>
	/// also except last dir, each dir is nonneglected by the cfg within that dir; last dir's cfg would be checked later outer of this scope.
	/// each dir is checked by its parent ensure it's not autogenerated.
	/// note: for the folder where this div is parented, the folder itself is not checked whether it's listable or dotLed or autogenerted or neglected.
	/// </summary>
	public interface IDelvable
	{
	}
}
