//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nilnul.dev.bak.nilnul0.dev.raws.bak_._retVoid {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    public sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
        
        public static Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection shields2bak {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["shields2bak"]));
            }
            set {
                this["shields2bak"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection srcs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["srcs"]));
            }
            set {
                this["srcs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection shieldsBaked {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["shieldsBaked"]));
            }
            set {
                this["shieldsBaked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bak")]
        public string bakBranch {
            get {
                return ((string)(this["bakBranch"]));
            }
            set {
                this["bakBranch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tmp")]
        public string tmpBranch {
            get {
                return ((string)(this["tmpBranch"]));
            }
            set {
                this["tmpBranch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection modulesBaked {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["modulesBaked"]));
            }
            set {
                this["modulesBaked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>vs</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection moduleRemoteKeysVs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["moduleRemoteKeysVs"]));
            }
            set {
                this["moduleRemoteKeysVs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>bitBucket</string>\r\n  <string>bitbucket</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection moduleRemoteKeysBitbucket {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["moduleRemoteKeysBitbucket"]));
            }
            set {
                this["moduleRemoteKeysBitbucket"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>aws</string>\r\n  <string>aw</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection moduleRemoteKeysAws {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["moduleRemoteKeysAws"]));
            }
            set {
                this["moduleRemoteKeysAws"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>gitLab</string>\r\n  <string>gitlab</string>\r\n  <string>gl</string>\r\n</Array" +
            "OfString>")]
        public global::System.Collections.Specialized.StringCollection moduleRemoteKeysGitlab {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["moduleRemoteKeysGitlab"]));
            }
            set {
                this["moduleRemoteKeysGitlab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>awVsGlBb</string>\r\n  <string>awGlBbVs</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection moduleRemoteKeysVsGlAwsBb {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["moduleRemoteKeysVsGlAwsBb"]));
            }
            set {
                this["moduleRemoteKeysVsGlAwsBb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string vsPrefix {
            get {
                return ((string)(this["vsPrefix"]));
            }
            set {
                this["vsPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string vsAcc {
            get {
                return ((string)(this["vsAcc"]));
            }
            set {
                this["vsAcc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection slnsBaked {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["slnsBaked"]));
            }
            set {
                this["slnsBaked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>bak_awGlVs</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection moduleRemoteAwGlVs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["moduleRemoteAwGlVs"]));
            }
            set {
                this["moduleRemoteAwGlVs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection shieldsNotBaked {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["shieldsNotBaked"]));
            }
            set {
                this["shieldsNotBaked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection modulesNotBakedInside {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["modulesNotBakedInside"]));
            }
            set {
                this["modulesNotBakedInside"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string module2bak {
            get {
                return ((string)(this["module2bak"]));
            }
            set {
                this["module2bak"] = value;
            }
        }
    }
}
